/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author stian
 */
public class discoveryWindow extends javax.swing.JFrame {

    /**
     * Creates new form discoveryWindow
     */
    public discoveryWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thisComputerLabel = new javax.swing.JLabel();
        computer1 = new Frontend.Computer();
        computer2 = new Frontend.Computer();
        computer3 = new Frontend.Computer();
        computer4 = new Frontend.Computer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        thisComputerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/radio_large.png"))); // NOI18N
        getContentPane().add(thisComputerLabel);

        computer1.setText("computer1");
        getContentPane().add(computer1);

        computer2.setText("computer2");
        getContentPane().add(computer2);

        computer3.setText("computer3");
        getContentPane().add(computer3);

        computer4.setText("computer4");
        getContentPane().add(computer4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Frontend.Computer computer1;
    private Frontend.Computer computer2;
    private Frontend.Computer computer3;
    private Frontend.Computer computer4;
    private javax.swing.JLabel thisComputerLabel;
    // End of variables declaration//GEN-END:variables
}
